kind: Deployment
apiVersion: apps/v1
metadata:
  name: <CHARTNAME>-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: <CHARTNAME>
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: <CHARTNAME>
  template:
    metadata:
      labels:
        app: <CHARTNAME>
    spec:
      containers:
        {{- with .Values.deployment.container }}
      - name: {{ .name | quote }}
        image: "{{ .repository }}{{ .image }}:{{ .tag }}"
        ports:
        - containerPort: {{ .containerPort }}
        {{- end }}