apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <CHARTNAME>-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  {{- include "ingress.rules" . | nindent 2 }}