apiVersion: v1
kind: Service
metadata:
  name: <CHARTNAME>-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: <CHARTNAME>
  ports:
  {{- with .Values.service }}
  - protocol: {{ .protocol }}
    targetPort: {{ .targetPort }}
    port: {{ .port }}
  {{- end }}